# azure-pipelines-expo-go.yml
trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: NODE_VERSION
    value: '18.x'

stages:
- stage: Deploy
  displayName: 'Deploy to Expo Go'
  jobs:
  - job: DeployToExpoGo
    displayName: 'Start Expo Go Server'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Install Node.js'

    - script: |
        npm install -g @expo/cli
      displayName: 'Install Expo CLI'

    - script: |
        npm install
      displayName: 'Install Dependencies'

    - script: |
        npx expo install --fix
      displayName: 'Install Expo Dependencies'

    - script: |
        # Start Expo Go (not development build)
        echo "Starting Expo Go with tunnel..."
        echo "QR Code will appear below:"
        echo ""
        
        # Start Expo Go with tunnel
        npx expo start --go --tunnel --no-dev --minify &
        EXPO_PID=$!
        
        # Wait for tunnel to be ready
        sleep 15
        
        # Get the tunnel URL and generate QR code
        TUNNEL_URL=$(npx expo start --go --tunnel --no-dev --minify --json 2>/dev/null | grep -o '"url":"[^"]*"' | head -1 | cut -d'"' -f4)
        
        if [ -n "$TUNNEL_URL" ]; then
          echo "Expo Go URL: $TUNNEL_URL"
          echo ""
          echo "QR Code:"
          npm install -g qrcode-terminal
          npx qrcode-terminal "$TUNNEL_URL"
        else
          echo "Failed to get tunnel URL"
          exit 1
        fi
        
        # Keep running
        wait $EXPO_PID
      env:
        EXPO_TOKEN: $(EXPO_TOKEN)
      displayName: 'Start Expo Go with QR Code'